### PR TITLE
Fix Markdown formatting

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by jdubois** [comment]
Sorry, this is totally wrong - why did you do a PR on a sample generated project? This broke my automatic generation script, I need to revert this

**Comment by valery1707** [comment]
`README.md` was generated too?

**Comment by jdubois** [comment]
yes everything is generated here

**Comment by valery1707** [comment]
Can you tell me where I can fix the source of generated `README.md`?

**Comment by valery1707** [comment]
I found and create PR https://github.com/jhipster/generator-jhipster/pull/5145

**Comment by jdubois** [comment]
Perfect :-)

**Pull request merged**
